export type SectionCategory =
  | "hero"
  | "features"
  | "social-proof"
  | "cta"
  | "forms"
  | "media"
  | "layout"

export const SECTION_CATEGORY_LABELS: Record<SectionCategory, string> = {
  hero: "Hero",
  features: "Özellikler",
  "social-proof": "Sosyal Kanıt",
  cta: "Çağrı (CTA)",
  forms: "Formlar",
  media: "Medya",
  layout: "Düzen",
}

export type SectionTypeInfo = {
  type: string
  label: string
  description: string
  category?: SectionCategory
  defaultConfig: Record<string, unknown>
}

export function getCategoryForType(type: string): SectionCategory {
  return CATEGORY_MAP[type] || "layout"
}

// Centralized category mapping — keep entries minimal in getSectionTypes()
const CATEGORY_MAP: Record<string, SectionCategory> = {
  // Hero
  "hero-statement": "hero",
  "hero-shade": "hero",
  "hero-audio-reactive": "hero",
  "hero-video": "hero",
  "hero-gradient": "hero",
  "hero-text-image": "hero",
  "main-hero": "hero",
  // Features
  "advantages-x-premium": "features",
  "imweb-me-stats-6": "features",
  "feature-storytelling": "features",
  "features-block": "features",
  "feature-grid": "features",
  "tech-specs": "features",
  "image-text-split": "features",
  "saaspo-feature-linear": "features",
  "saaspo-feature-sections-voiceflow": "features",
  "spatial-product-showcase": "features",
  "stats-counter": "features",
  // Social Proof
  "logo-cloud": "social-proof",
  "testimonials-v2": "social-proof",
  "urunler-slide": "social-proof",
  // CTA
  "purchase-cta": "cta",
  "cta-banner": "cta",
  "hookable-ai-cta-3": "cta",
  "cta-illustration": "cta",
  "pricing-table": "cta",
  // Forms
  "contact-form": "forms",
  "faq-accordion": "forms",
  // Media
  "full-bleed-media": "media",
  // Layout
  "bento-grid": "layout",
  "bento-box": "layout",
  "product-hero": "hero",
  // VT template sections
  "vt-hero": "hero",
  "vt-features": "features",
  "vt-how-it-works": "features",
  "vt-metrics": "features",
  "vt-integrations": "features",
  "vt-infrastructure": "features",
  "vt-security": "features",
  "vt-developers": "features",
  "vt-pricing": "cta",
  "vt-testimonials": "social-proof",
  "vt-cta": "cta",
  "conversion-integrations-section": "features",
  // ST template sections
  "st-hero": "hero",
  "st-features": "features",
  "st-how-it-works": "features",
  "st-metrics": "features",
  "st-integrations": "features",
  "st-infrastructure": "features",
  "st-security": "features",
  "st-developers": "features",
  "st-pricing": "cta",
  "st-testimonials": "social-proof",
  "st-cta": "cta",
  // NEXO template sections
  "nexo-hero": "hero",
  "nexo-features": "features",
  "nexo-ai-section": "features",
  "nexo-vercel-section": "features",
  // NEXUS template sections (ASCII animations)
  "nexus-hero": "hero",
  "nexus-features": "features",
  "nexus-how-it-works": "features",
  "nexus-infrastructure": "features",
  "nexus-metrics": "features",
  "nexus-integrations": "features",
  "nexus-security": "features",
  "nexus-developers": "features",
  "nexus-cta": "cta",
  "animated-roadmap": "hero",
  // SPLIT template sections (3D hero + Sprint-style)
  "split-hero-3d": "hero",
  "split-logo-cloud": "social-proof",
  "split-feature-cards": "features",
  "split-ai-section": "features",
  "split-workflows": "features",
  "split-product-direction": "features",
  "split-cta": "cta",
  "clip-hover-grid": "features",
  "single-pricing-card": "cta",
  "single-pricing-card-3col": "cta",
  "immersive-gallery": "media",
  "benchmark-charts": "features",
  "feature-section-1": "features",
  "riotters-hero": "features",
  // Azurio Branding Studio sections
  "st-aero-hero-1": "hero",
  "st-tabs": "features",
  "st-lets-work": "cta",
  "st-marquee": "media",
  "az-hero": "hero",
  "az-projects-stack": "media",
  "az-sticky-caption": "features",
  "az-sticky-images": "media",
  "az-manifest-split": "features",
  "az-parallax-divider": "media",
  "az-blog-grid": "layout",
  "az-cta-marquee": "cta",
  // Skiper crowd canvas
  "crowd-canvas": "media",
  // Hover brand logo
  "hover-brand-logo": "social-proof",
  // CodeNest hero (HLS video + liquid glass card)
  "code-nest-hero": "hero",
  // Pixel Blast (WebGL interactive hero)
  "pixel-blast-hero": "hero",
  // Masonry Gallery
  "masonry-gallery": "media",
  // Scroll Blur Typography
  "scroll-blur-typography": "layout",
  // Liveblocks-style dark hero
  "liveblocks-home-hero": "hero",
  // Customers Showcase
  "customers-showcase": "social-proof",
  "feature-carousel": "features",
  // Perspective Hero (Three.js HTML→Canvas projection)
  "perspective-hero": "hero",
}

export function getSectionTypes(): SectionTypeInfo[] {
  return [
    {
      type: "product-hero",
      label: "Ürün Hero",
      description: "Seçilen ürünün 3-sütunlu detay hero'su (başlık, görsel, specs + çözümler + etiketler)",
      defaultConfig: {
        productId: "",
        dark: true,
      },
    },
    {
      type: "hero-statement",
      label: "Hero Statement",
      description: "Dev tipografi, animasyonlu ana başlık",
      defaultConfig: {
        headline: "Başlık Buraya",
        subheadline: "",
        description: "",
        ctaText: "Teklif İste",
        ctaHref: "/iletisim",
        secondaryCtaText: "",
        secondaryCtaHref: "",
        image: "",
        dark: true,
      },
    },
    {
      type: "hero-audio-reactive",
      label: "Hero Audio Reactive",
      description: "Canvas dalga animasyonu, müzik reaktif, film grain efektli",
      defaultConfig: {
        tagline: "",
        headline: "Başlık Buraya",
        headlineSecondLine: "",
        subtitle: "",
        creditText: "",
        audioSrc: "",
        dark: true,
      },
    },
    {
      type: "hero-shade",
      label: "Hero Shade",
      description: "Gradient glow + BorderBeam animasyonlu hero, görsel kartlı",
      defaultConfig: {
        headline: "Başlık Buraya",
        description: "",
        ctaText: "Teklif İste",
        ctaHref: "/iletisim",
        secondaryCtaText: "",
        secondaryCtaHref: "",
        image: "",
        imageAlt: "",
        beamColorFrom: "#ffaa40",
        beamColorTo: "#9c40ff",
        dark: true,
      },
    },
    {
      type: "hero-video",
      label: "Hero Video",
      description: "Arka plan videolu hero, logo banner ile",
      defaultConfig: {
        headline: "Başlık Buraya",
        description: "",
        ctaText: "Teklif İste",
        ctaHref: "/iletisim",
        secondaryCtaText: "",
        secondaryCtaHref: "",
        videoSrc: "",
        height: "large",
        showLogoBanner: false,
        logoBannerText: "En iyi ekiplerin tercihi",
        logos: [],
        dark: true,
      },
    },
    {
      type: "imweb-me-stats-6",
      label: "Metrik Görsel",
      description: "Animasyonlu bar grafik + video + sayaçlı istatistikler, ortalanmış layout",
      defaultConfig: {
        mode: "light",
        title: "Büyüyen\nEn Hızlı Platform",
        videoUrl: "https://static-v2.imweb.me/io/home/growth-graph-video.mp4",
        mainStatLabel: "2025 Kümülatif Site Açılışı",
        mainStatValue: 100,
        mainStatUnit: "万",
        bars: [
          { year: "2021", value: null },
          { year: "2022", value: null },
          { year: "2023", value: 60, unit: "万" },
          { year: "2024", value: 80, unit: "万" },
        ],
        bottomStats: [
          { label: "Yıllık Ortalama İşlem Büyümesi", value: "342", unit: "%", hasGradient: true },
          { label: "Müşteri İşlem Hacmi", value: "6", unit: "Trilyon", hasGradient: false },
          { label: "Tasarımcı & Uzman Sayısı", value: "4000", unit: "Kişi", hasGradient: false },
        ],
      },
    },
    {
      type: "advantages-x-premium",
      label: "Temel Özellikler (3 Kolon)",
      description: "Siyah arka plan, 3 özellik kartı, ikonlu, animasyonlu",
      defaultConfig: {
        heading: "Temel Özellikler",
        advantages: [
          { icon: "trending-up", title: "Hızlı VIP Destek", description: "Öncelikli destek ekibimizle sorunlarınızı hızla çözün." },
          { icon: "x-grok", title: "Premium+ ve Grok", description: "Tüm premium özellikler ve gelişmiş AI yeteneklerine erişin." },
          { icon: "profile-shield", title: "Özel Profil", description: "İşletmenizi öne çıkarın, tüm bağlı hesapları tek yerden yönetin." },
        ],
        ctaText: "Sorularınız için destek ekibimize ulaşın",
        ctaHref: "#",
      },
    },
    {
      type: "spatial-product-showcase",
      label: "Ürün Showcase (Sekmeli)",
      description: "Dinamik sekmeli ürün showcase — istediğiniz kadar ürün ekleyin, animasyonlu geçiş, özellik çubukları",
      defaultConfig: {
        products: [
          {
            label: "Sol",
            title: "Spatial Anchor",
            description: "The primary node for binaural synchronization. Handles low-latency transmission and anchors the spatial audio soundstage.",
            image: "https://ik.imagekit.io/kqmrslzuq/SOUND/left-earbud.png",
            gradientClass: "from-blue-600 to-indigo-900",
            glowClass: "bg-blue-500",
            ringClass: "border-l-blue-500/50",
            connectionStatus: "Connected",
            batteryLevel: 82,
            features: [
              { label: "Latency", value: 12, icon: "zap" },
              { label: "Sync Rate", value: 98, icon: "wifi" },
            ],
          },
          {
            label: "Sağ",
            title: "Vocal Clarity",
            description: "Optimized for high-frequency detail and voice pickup. Contains the beamforming microphone array for crystal clear calls.",
            image: "https://ik.imagekit.io/kqmrslzuq/SOUND/right-earbud.png",
            gradientClass: "from-emerald-600 to-teal-900",
            glowClass: "bg-emerald-500",
            ringClass: "border-r-emerald-500/50",
            connectionStatus: "Connected",
            batteryLevel: 74,
            features: [
              { label: "Bitrate", value: 94, icon: "bluetooth" },
              { label: "Clarifier", value: 88, icon: "music" },
            ],
          },
        ],
      },
    },
    {
      type: "saaspo-feature-sections-voiceflow",
      label: "Saaspo Feature (Voiceflow)",
      description: "Koyu zemin, ASCII küre görseli, 4 özellik kartı, logo bar — enterprise feature section",
      defaultConfig: {
        badge: "Enterprise Cloud",
        title: "Ölçek ve Güvenlik\nStuux Enterprise ile",
        description: "Ürün ekipleri; onaylı LLM'lerini, müşteri verileri ve teknoloji yığını entegrasyonlarını kullanarak gelişmiş AI ajanlarını güvenle oluşturur ve dağıtır.",
        ctaText: "Enterprise Cloud'u Keşfet",
        ctaHref: "#",
        features: [
          { icon: "platform", title: "AI platform of record", description: "Her ekip için merkezi, güvenli bir platformda AI ürünleri oluşturun, ölçeklendirin ve iş birliği yapın." },
          { icon: "rocket", title: "Fikirleri hızla pazara taşıyın", description: "Hız ve kaliteyle ürün geliştirirken yeni kullanım senaryolarına verimli şekilde ölçeklendirin." },
          { icon: "lock", title: "Vendor lock-in'den kaçının", description: "AI'ya bahis yapın, tek satıcıya değil. Değişen LLM teknolojilerine uyum sağlayın." },
          { icon: "download", title: "Kontrol & özelleştirme", description: "Güvenli guardrail'larla herhangi bir LLM modeliyle sınırsız API entegrasyonu oluşturun." },
        ],
        trustedByText: "Sektörün en iyileri tarafından güvenilir",
        logos: [
          { name: "Instacart" }, { name: "Intrado" }, { name: "Intuit" }, { name: "KBC" }, { name: "Louis Vuitton" },
        ],
      },
    },
    {
      type: "feature-storytelling",
      label: "Feature Storytelling",
      description: "Başlık + açıklama + büyük görsel (sağ-sol layout)",
      defaultConfig: {
        label: "",
        headline: "Özellik Başlığı",
        description: "",
        image: "",
        reverse: false,
        dark: true,
      },
    },
    {
      type: "features-block",
      label: "Features Block",
      description: "Başlık + marquee etiketler + 4 özellik kartı, dashed border",
      defaultConfig: {
        headline: "Neden Bizi Tercih Etmelisiniz?",
        description: "",
        marqueeItems: [],
        features: [
          { title: "Özellik 1", description: "Açıklama", icon: "zap" },
          { title: "Özellik 2", description: "Açıklama", icon: "target" },
          { title: "Özellik 3", description: "Açıklama", icon: "shield" },
          { title: "Özellik 4", description: "Açıklama", icon: "heart" },
        ],
        dark: true,
      },
    },
    {
      type: "feature-grid",
      label: "Feature Grid",
      description: "2x2 veya 3x3 border-based özellik kartları",
      defaultConfig: {
        headline: "",
        columns: 2,
        items: [
          { title: "Özellik 1", description: "Açıklama", icon: "" },
          { title: "Özellik 2", description: "Açıklama", icon: "" },
          { title: "Özellik 3", description: "Açıklama", icon: "" },
          { title: "Özellik 4", description: "Açıklama", icon: "" },
        ],
        dark: true,
      },
    },
    {
      type: "full-bleed-media",
      label: "Full-Bleed Media",
      description: "Tam genişlik görsel veya video, parallax efekti",
      defaultConfig: {
        image: "",
        video: "",
        alt: "",
        caption: "",
        aspectRatio: "video",
        parallax: true,
        dark: true,
      },
    },
    {
      type: "tech-specs",
      label: "Tech Specs",
      description: "Gruplu teknik özellik tabloları",
      defaultConfig: {
        headline: "Teknik Özellikler",
        description: "",
        groups: [
          {
            title: "Genel",
            specs: [
              { label: "Özellik", value: "Değer" },
            ],
          },
        ],
        dark: true,
      },
    },
    {
      type: "purchase-cta",
      label: "Purchase CTA",
      description: "Fiyat + CTA butonları, vurgulu section",
      defaultConfig: {
        headline: "Hemen Sipariş Verin",
        description: "",
        price: "",
        priceNote: "",
        ctaText: "Teklif İste",
        ctaHref: "/iletisim",
        secondaryCtaText: "",
        secondaryCtaHref: "",
        dark: true,
      },
    },
    {
      type: "bento-grid",
      label: "Bento Grid (Animated)",
      description: "6 slotlu animasyonlu bento grid, istatistik ve özellik kartları",
      defaultConfig: {
        headline: "",
        subheadline: "",
        items: [
          { title: "Özellik 1", description: "Açıklama", stat: "", badge: "", image: "" },
          { title: "Özellik 2", description: "Açıklama", stat: "", badge: "", image: "" },
          { title: "", description: "", stat: "10X", badge: "", image: "" },
          { title: "Özellik 4", description: "Açıklama", stat: "42%", badge: "Yeni", image: "" },
          { title: "Özellik 5", description: "Açıklama", stat: "", badge: "", image: "" },
          { title: "Özellik 6", description: "Geniş alt kart açıklaması", stat: "", badge: "", image: "" },
        ],
        dark: true,
      },
    },
    {
      type: "bento-box",
      label: "Bento Box",
      description: "Harita, mesaj, istatistik ve grafik grid'i",
      defaultConfig: {
        topLeftLabel: "Gerçek zamanlı konum takibi",
        topLeftDescription: "Gelişmiş takip sistemi ile tüm varlıklarınızı anında bulun.",
        topLeftMapBadge: "Son bağlantı: Türkiye",
        topRightLabel: "E-posta ve web destek",
        topRightDescription: "İhtiyacınız olan yardım için e-posta veya web üzerinden bize ulaşın.",
        centerStat: "%99.99 Çalışma Süresi",
        bottomLabel: "Aktivite akışı",
        bottomDescription: "Uygulamanızın aktivitesini gerçek zamanlı izleyin.",
        dark: true,
      },
    },
    {
      type: "logo-cloud",
      label: "Logo Cloud",
      description: "Sonsuz kayan logo şeridi, mask gradient efektli",
      defaultConfig: {
        headline: "",
        subheadline: "",
        logos: [],
        speed: 80,
        reverse: false,
        dark: true,
      },
    },
    {
      type: "saaspo-feature-linear",
      label: "Saaspo Feature (Linear)",
      description: "Linear tarzi timeline + proje kartlari + ozellik grid'i",
      defaultConfig: {
        badge: "Project and long-term planning",
        title: "Set the product direction",
        description: "Align your team around a unified product timeline. Plan, manage, and track all product initiatives with Linear's visual planning tools.",
      },
    },
    {
      type: "stats-counter",
      label: "Stats Counter",
      description: "Vurgulu büyük rakamlar, 2-4 sütun",
      defaultConfig: {
        headline: "",
        description: "",
        stats: [
          { value: "500+", label: "Teslim Edilen Sistem" },
          { value: "200+", label: "Mutlu Müşteri" },
          { value: "10+", label: "Yıllık Deneyim" },
          { value: "3 Yıl", label: "Garanti" },
        ],
        dark: false,
      },
    },
    {
      type: "faq-accordion",
      label: "FAQ Accordion",
      description: "Sıkça sorulan sorular, tıklayınca açılan",
      defaultConfig: {
        headline: "Sıkça Sorulan Sorular",
        description: "",
        items: [
          { question: "Soru 1", answer: "Cevap 1" },
          { question: "Soru 2", answer: "Cevap 2" },
          { question: "Soru 3", answer: "Cevap 3" },
        ],
        dark: false,
      },
    },
    {
      type: "contact-form",
      label: "İletişim Formu",
      description: "Tam fonksiyonel iletişim formu (CRM'e ticket olarak düşer)",
      defaultConfig: {
        headline: "İletişim",
        description: "Sorularınız ve teklif talepleriniz için bizimle iletişime geçin.",
        email: "info@stuux.com",
        phone: "",
        address: "",
        categories: ["Teklif İste", "Genel Bilgi", "Teknik Destek", "İş Ortaklığı", "Diğer"],
        dark: false,
      },
    },
    {
      type: "pricing-table",
      label: "Pricing Table",
      description: "3 sütunlu fiyatlandırma kartları, vurgulanmış plan ile",
      defaultConfig: {
        headline: "Fiyatlandırma",
        description: "İhtiyacınıza uygun planı seçin",
        plans: [
          {
            name: "Başlangıç",
            price: "₺X",
            priceNote: "/aylık",
            description: "Küçük ekipler için",
            features: ["Özellik 1", "Özellik 2", "Özellik 3"],
            ctaText: "Başla",
            ctaHref: "/iletisim",
            highlighted: false,
          },
          {
            name: "Profesyonel",
            price: "₺Y",
            priceNote: "/aylık",
            description: "Büyüyen işletmeler için",
            features: ["Tüm Başlangıç özellikleri", "Özellik 4", "Özellik 5", "Özellik 6"],
            ctaText: "Başla",
            ctaHref: "/iletisim",
            highlighted: true,
          },
          {
            name: "Kurumsal",
            price: "Özel",
            priceNote: "",
            description: "Büyük organizasyonlar için",
            features: ["Tüm Profesyonel özellikleri", "Özel destek", "SLA garantisi"],
            ctaText: "İletişime Geç",
            ctaHref: "/iletisim",
            highlighted: false,
          },
        ],
        dark: false,
      },
    },
    {
      type: "image-text-split",
      label: "Image + Text Split",
      description: "İki sütun: görsel + başlık/açıklama/bullet/CTA",
      defaultConfig: {
        label: "",
        headline: "Başlık",
        description: "",
        bullets: [],
        image: "",
        imageAlt: "",
        ctaText: "",
        ctaHref: "",
        reverse: false,
        dark: false,
      },
    },
    {
      type: "cta-banner",
      label: "CTA Banner",
      description: "Vurgulu çağrı bandı, gradient/solid/minimal varyantlı",
      defaultConfig: {
        headline: "Hemen Başlayın",
        description: "",
        ctaText: "Teklif İste",
        ctaHref: "/iletisim",
        secondaryCtaText: "",
        secondaryCtaHref: "",
        variant: "gradient",
      },
    },
    {
      type: "hookable-ai-cta-3",
      label: "Hookable AI CTA 3",
      description: "Animasyonlu dönen pain-point listesi, gradient başlık, light/dark mod",
      defaultConfig: {
        mode: "light",
        heading: "Say Goodbye to",
        painPoints: [
          "눈치보이는 디자이너와의 소통",
          "막막한 기획",
          "값비싼 외주비용",
          "내 제품을 잘 모르는 AI",
          "엄청난 시간 소모",
          "막막한 디자인",
          "경쟁사 디자인 베끼기",
        ],
        animationDuration: 2000,
      },
    },
    {
      type: "hero-gradient",
      label: "Hero Gradient",
      description: "Animasyonlu gradient blob, grid overlay, vurgulu başlık, modern hero",
      defaultConfig: {
        badge: "",
        headline: "Profesyoneller İçin",
        highlight: "Yüksek Performans",
        description: "İhtiyacınıza özel donanım çözümleri.",
        ctaText: "Ürünleri İncele",
        ctaHref: "/urunler",
        secondaryCtaText: "Uzmanla Konuş",
        secondaryCtaHref: "/iletisim",
        image: "",
      },
    },
    {
      type: "hero-text-image",
      label: "Hero Text + Video BG",
      description: "HLS video arka plan, dönen video ikonlar, gradient başlık, glowing CTA butonu",
      defaultConfig: {},
    },
    {
      type: "main-hero",
      label: "Main Hero",
      description: "Tam ekran fade slideshow, çift satır başlık ve sayaç",
      defaultConfig: {
        slides: [
          { img: "", line1: "BAŞLIK", line2: "İKİNCİ SATIR" },
          { img: "", line1: "BAŞLIK 2", line2: "İKİNCİ SATIR" },
          { img: "", line1: "BAŞLIK 3", line2: "İKİNCİ SATIR" },
        ],
      },
    },
    {
      type: "testimonials-v2",
      label: "Testimonials V2",
      description: "3 kolonlu dikey kayan müşteri yorumları, framer-motion animasyonlu",
      defaultConfig: {
        badge: "Yorumlar",
        headline: "Kullanıcılarımız ne diyor?",
        description: "Ekiplerin platformumuzla operasyonlarını nasıl kolaylaştırdığını keşfedin.",
        testimonials: [
          { text: "", image: "", name: "", role: "" },
          { text: "", image: "", name: "", role: "" },
          { text: "", image: "", name: "", role: "" },
        ],
        dark: false,
      },
    },
    {
      type: "urunler-slide",
      label: "Ürünler Slide",
      description: "Marquee ürün/üye kartları, başlık ve opsiyonel testimonial",
      defaultConfig: {
        headline: "Ürünlerimiz",
        description: "",
        members: [
          { image: "", name: "Ürün 1", role: "Açıklama" },
          { image: "", name: "Ürün 2", role: "Açıklama" },
          { image: "", name: "Ürün 3", role: "Açıklama" },
          { image: "", name: "Ürün 4", role: "Açıklama" },
        ],
        testimonial: "",
        testimonialName: "",
        testimonialRole: "",
        testimonialImage: "",
        dark: false,
      },
    },
    // ============================================================
    // VT Template Sections (Vercel import, theme-aware, fixed content)
    // ============================================================
    {
      type: "vt-hero",
      label: "VT · Hero (ASCII/Video)",
      description: "Vercel template hero: video arka plan, animasyonlu blur kelime, istatistikler",
      defaultConfig: {},
    },
    {
      type: "vt-features",
      label: "VT · Features",
      description: "Vercel template features: bento card + canvas particle animasyonu",
      defaultConfig: {},
    },
    {
      type: "vt-how-it-works",
      label: "VT · How It Works",
      description: "Vercel template nasıl çalışır akışı",
      defaultConfig: {},
    },
    {
      type: "vt-metrics",
      label: "VT · Metrics",
      description: "Vercel template metrik göstergeleri (büyük rakamlar)",
      defaultConfig: {},
    },
    {
      type: "vt-integrations",
      label: "VT · Integrations",
      description: "Vercel template entegrasyonlar grid'i",
      defaultConfig: {},
    },
    {
      type: "vt-infrastructure",
      label: "VT · Infrastructure",
      description: "Vercel template altyapı / mimari bölümü",
      defaultConfig: {},
    },
    {
      type: "vt-security",
      label: "VT · Security",
      description: "Vercel template güvenlik/compliance bölümü",
      defaultConfig: {},
    },
    {
      type: "vt-developers",
      label: "VT · Developers",
      description: "Vercel template developer bölümü (kod örneği)",
      defaultConfig: {},
    },
    {
      type: "vt-pricing",
      label: "VT · Pricing",
      description: "Vercel template fiyatlandırma tablosu",
      defaultConfig: {},
    },
    {
      type: "vt-testimonials",
      label: "VT · Testimonials",
      description: "Vercel template müşteri yorumları",
      defaultConfig: {},
    },
    {
      type: "vt-cta",
      label: "VT · CTA",
      description: "Vercel template son CTA bölümü",
      defaultConfig: {},
    },
    {
      type: "st-hero",
      label: "ST · Hero (Sphere)",
      description: "ST template: animasyonlu küre arka plan, blur kelime döngüsü",
      defaultConfig: {},
    },
    {
      type: "st-features",
      label: "ST · Features",
      description: "ST template features bölümü",
      defaultConfig: {},
    },
    {
      type: "st-how-it-works",
      label: "ST · How It Works",
      description: "ST template nasıl çalışır bölümü",
      defaultConfig: {},
    },
    {
      type: "st-metrics",
      label: "ST · Metrics",
      description: "ST template metrikler bölümü",
      defaultConfig: {},
    },
    {
      type: "st-integrations",
      label: "ST · Integrations",
      description: "ST template entegrasyonlar bölümü",
      defaultConfig: {},
    },
    {
      type: "st-infrastructure",
      label: "ST · Infrastructure",
      description: "ST template altyapı bölümü",
      defaultConfig: {},
    },
    {
      type: "st-security",
      label: "ST · Security",
      description: "ST template güvenlik bölümü",
      defaultConfig: {},
    },
    {
      type: "st-developers",
      label: "ST · Developers",
      description: "ST template geliştiriciler bölümü",
      defaultConfig: {},
    },
    {
      type: "st-pricing",
      label: "ST · Pricing",
      description: "ST template fiyatlandırma bölümü",
      defaultConfig: {},
    },
    {
      type: "st-testimonials",
      label: "ST · Testimonials",
      description: "ST template referanslar bölümü",
      defaultConfig: {},
    },
    {
      type: "st-cta",
      label: "ST · CTA (Tetrahedron)",
      description: "ST template son CTA, animasyonlu tetrahedron",
      defaultConfig: {},
    },
    {
      type: "nexo-hero",
      label: "NEXO · Hero",
      description: "NEXO template hero bölümü",
      defaultConfig: {
        brandNameLight: "NEXORA",
        brandNameBold: "SIM",
        brandSuperscript: "™",
        subtitleLine1: "MYANMAR'S NEXT-GEN ESIM INFRASTRUCTURE",
        subtitleLine2: "AI-DRIVEN • GSMA-COMPLIANT • VERCEL-POWERED",
        statusItems: [
          { label: "SYSTEM ACTIVE", icon: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>` },
          { label: "GSMA CERTIFIED", icon: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>` },
          { label: "AI ENABLED", icon: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a5 5 0 0 1 5 5v3a5 5 0 0 1-10 0V7a5 5 0 0 1 5-5z"/><path d="M2 17a10 10 0 0 1 20 0"/></svg>` },
          { label: "VERCEL EDGE", icon: `<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>` },
        ],
        stats: [
          { value: "99.9%", label: "UPTIME" },
          { value: "<30ms", label: "LATENCY" },
          { value: "24/7", label: "SUPPORT" },
          { value: "SGP.22", label: "COMPLIANT" },
        ],
      },
    },
    {
      type: "nexo-features",
      label: "NEXO · Features",
      description: "NEXO template features (ICCID search, CPU, QR)",
      defaultConfig: {},
    },
    {
      type: "nexo-ai-section",
      label: "NEXO · AI Section",
      description: "NEXO template AI/workflow bölümü",
      defaultConfig: {},
    },
    {
      type: "nexo-vercel-section",
      label: "NEXO · Vercel Section",
      description: "NEXO template edge/deployment bölümü",
      defaultConfig: {},
    },
    {
      type: "nexus-hero",
      label: "NEXUS · Hero (ASCII Wave)",
      description: "NEXUS template hero: ASCII dalga arka planı, istatistik kartları",
      defaultConfig: {},
    },
    {
      type: "nexus-features",
      label: "NEXUS · Features",
      description: "NEXUS template features: animasyonlu ASCII iconlar + dönen küp",
      defaultConfig: {
        badge: "// PLATFORM",
        headingLine1: "Ölçeklenmek için",
        headingLine2: "gerek duyduğunuz her şey.",
        description: "AI uygulamaları kurmak, dağıtmak ve ölçeklendirmek için eksiksiz bir platform. Prototip'ten üretime aylar değil, dakikalar.",
        features: [
          { title: "Neural Processing", description: "Gelişmiş derin öğrenme modelleri; bağlamı anlar ve işinize uyarlanır.", animationKey: "neural" },
          { title: "Akıllı İş Akışları", description: "Sürükle-bırak kolaylığıyla görsel workflow builder. AI aksiyonlarını zincirleyin.", animationKey: "workflow" },
          { title: "Kurumsal Güvenlik", description: "SOC 2 Type II sertifikalı, uçtan uca şifreleme. Veriniz kontrolünüzde.", animationKey: "security" },
          { title: "Canlı Analitik", description: "Canlı dashboard'lar ve anlık içgörüler. Performansı anında optimize edin.", animationKey: "analytics" },
          { title: "Global Ölçek", description: "12 bölgede dağıtık altyapı. Dünyanın her yerinden 100ms altı gecikme.", animationKey: "globe" },
          { title: "API Öncelikli", description: "Kapsamlı SDK'larla REST ve GraphQL API'ler. Nexus'u her stack'e entegre edin.", animationKey: "api" },
        ],
      },
    },
    {
      type: "nexus-how-it-works",
      label: "NEXUS · How It Works",
      description: "NEXUS template nasıl çalışır: 3 adım + canlı kod önizleme",
      defaultConfig: {},
    },
    {
      type: "nexus-infrastructure",
      label: "NEXUS · Infrastructure",
      description: "NEXUS template global altyapı: ASCII DNA + bölge listesi",
      defaultConfig: {},
    },
    {
      type: "nexus-metrics",
      label: "NEXUS · Metrics",
      description: "NEXUS template canlı metrikler: animasyonlu sayaçlar + aktivite akışı",
      defaultConfig: {},
    },
    {
      type: "nexus-integrations",
      label: "NEXUS · Integrations",
      description: "NEXUS template entegrasyonlar: ASCII ikon kartları + API örneği",
      defaultConfig: {},
    },
    {
      type: "nexus-security",
      label: "NEXUS · Security",
      description: "NEXUS template güvenlik: ASCII torus arka plan + sertifikalar",
      defaultConfig: {},
    },
    {
      type: "nexus-developers",
      label: "NEXUS · Developers",
      description: "NEXUS template geliştiriciler: sekme'li kod blokları",
      defaultConfig: {},
    },
    {
      type: "nexus-cta",
      label: "NEXUS · CTA (ASCII Sphere)",
      description: "NEXUS template son CTA: animasyonlu ASCII küp + küre",
      defaultConfig: {},
    },
    {
      type: "animated-roadmap",
      label: "Animasyonlu Yol Haritası",
      description:
        "Hero başlığı + scroll ile çizilen SVG patika üzerinde milestone'lar (kick-off, tasarım, geliştirme, lansman)",
      defaultConfig: {
        headline: "Net bir ürün planıyla",
        highlightedWord: "öne",
        headlineSuffix: "geçin",
        description:
          "Yol haritanızı görselleştirin, görev atayın ve her kilometre taşına daha hızlı ulaşın.",
        primaryCtaText: "Ücretsiz başlayın",
        primaryCtaHref: "/iletisim",
        secondaryCtaText: "Nasıl çalışır?",
        secondaryCtaHref: "#",
        mapImageSrc: "",
        milestones: [
          { id: 1, name: "Başlangıç", status: "complete", top: "70%", left: "5%" },
          { id: 2, name: "Tasarım", status: "complete", top: "15%", left: "20%" },
          { id: 3, name: "Geliştirme", status: "in-progress", top: "45%", left: "55%" },
          { id: 4, name: "Lansman", status: "pending", top: "10%", right: "10%" },
        ],
      },
    },
    {
      type: "split-hero-3d",
      label: "SPLIT · 3D Hero",
      description: "SPLIT template hero: 3D perspective dashboard mockup + başlık",
      defaultConfig: {
        headline: "Ürün planlama ve geliştirme için özel olarak tasarlandı",
        description:
          "Modern yazılım geliştirme için tasarlanmış sistem.\nIssue, proje ve ürün yol haritalarını tek yerden yönetin.",
        primaryCtaText: "Kurmaya başla",
        primaryCtaHref: "/iletisim",
        secondaryCtaLabel: "Yeni:",
        secondaryCtaText: "Slack için Sprint agent",
        secondaryCtaHref: "#",
        backgroundImage: "",
      },
    },
    {
      type: "split-logo-cloud",
      label: "SPLIT · Logo Cloud",
      description: "SPLIT template logo bulutu: hover blur + CTA overlay",
      defaultConfig: {},
    },
    {
      type: "split-feature-cards",
      label: "SPLIT · Feature Cards",
      description: "SPLIT template özellik kartları: SVG illüstrasyonlu 3'lü grid",
      defaultConfig: {},
    },
    {
      type: "split-ai-section",
      label: "SPLIT · AI Section",
      description: "SPLIT template AI: 3D rotasyonlu agent dropdown + MCP kod bloğu",
      defaultConfig: {},
    },
    {
      type: "split-workflows",
      label: "SPLIT · Workflows",
      description: "SPLIT template entegrasyon carousel: Intercom, GitHub, Figma mockup'ları",
      defaultConfig: {},
    },
    {
      type: "split-product-direction",
      label: "SPLIT · Product Direction",
      description: "SPLIT template 3D zaman çizelgesi + proje kartları",
      defaultConfig: {},
    },
    {
      type: "split-cta",
      label: "SPLIT · CTA",
      description: "SPLIT template minimal CTA: başlık + 2 buton",
      defaultConfig: {},
    },
    {
      type: "single-pricing-card",
      label: "Tekli Fiyat Kartı",
      description: "İkonlu, referanslı premium fiyat kartı (özellik + testimonial carousel)",
      defaultConfig: {
        sectionBadgeText: "Fiyatlandırma",
        sectionBadgeIcon: "credit-card",
        sectionHeadline: "Tek paket, sınırsız ihtimal",
        sectionDescription: "İhtiyacınız olan her şey tek bir pakette.",
        badgeText: "Premium",
        badgeIcon: "crown",
        title: "STUUX Workstation",
        subtitle: "Profesyonel iş istasyonu paketi",
        priceCurrent: "₺69.999",
        priceOriginal: "₺99.999",
        priceDiscount: "%30 İndirim",
        featuresTitle: "Paket İçeriği",
        featuresIcon: "check",
        benefits: [
          { text: "Tek seferlik ödeme, ömür boyu güncelleme", icon: "check" },
          { text: "30 gün para iade garantisi", icon: "shield" },
          { text: "Türkiye'de üretim, yerinde destek", icon: "heart" },
        ],
        features: [
          { text: "Intel Core i9 / AMD Threadripper" },
          { text: "128 GB DDR5 RAM" },
          { text: "NVIDIA RTX 4090" },
          { text: "2 TB NVMe SSD" },
          { text: "Sessiz sıvı soğutma" },
          { text: "3 yıl garanti" },
        ],
        primaryButtonText: "Sipariş Ver",
        primaryButtonIcon: "shopping-cart",
        primaryButtonHref: "/iletisim",
        secondaryButtonText: "Özelleştir",
        secondaryButtonIcon: "external-link",
        secondaryButtonHref: "/yapilandirici",
        testimonials: [],
        testimonialRotationSpeed: 5000,
      },
    },
    {
      type: "single-pricing-card-3col",
      label: "Tekli Fiyat Kartı (3 Kolon)",
      description: "3 kolonlu fiyat kartı: fiyat + özellikler + zengin metin editörü",
      defaultConfig: {
        sectionBadgeText: "Fiyatlandırma",
        sectionBadgeIcon: "credit-card",
        sectionHeadline: "Tek paket, sınırsız ihtimal",
        sectionDescription: "İhtiyacınız olan her şey tek bir pakette.",
        badgeText: "Premium",
        badgeIcon: "crown",
        title: "STUUX Workstation",
        subtitle: "Profesyonel iş istasyonu paketi",
        priceCurrent: "₺69.999",
        priceOriginal: "₺99.999",
        priceDiscount: "%30 İndirim",
        featuresTitle: "Paket İçeriği",
        featuresIcon: "check",
        benefits: [
          { text: "Tek seferlik ödeme, ömür boyu güncelleme", icon: "check" },
          { text: "30 gün para iade garantisi", icon: "shield" },
          { text: "Türkiye'de üretim, yerinde destek", icon: "heart" },
        ],
        features: [
          { text: "Intel Core i9 / AMD Threadripper" },
          { text: "128 GB DDR5 RAM" },
          { text: "NVIDIA RTX 4090" },
          { text: "2 TB NVMe SSD" },
          { text: "Sessiz sıvı soğutma" },
          { text: "3 yıl garanti" },
        ],
        richTitle: "Detaylar",
        richContent: "<p>Bu alanı zengin metin editörü ile özelleştirebilirsiniz. <strong>Kalın</strong>, <em>italik</em>, listeler ve daha fazlası.</p>",
        primaryButtonText: "Sipariş Ver",
        primaryButtonIcon: "shopping-cart",
        primaryButtonHref: "/iletisim",
        secondaryButtonText: "Özelleştir",
        secondaryButtonIcon: "external-link",
        secondaryButtonHref: "/yapilandirici",
      },
    },
    {
      type: "riotters-hero",
      label: "Ürün-Detay",
      description: "İki kolonlu ürün detay: sol alıntı + sağ başlık ve 4'lü görsel kolajı",
      defaultConfig: {
        headlineLine1: "Detaylı tasarım,",
        headlineLine2: "üstün",
        highlightedWord: "performans",
        authorName: "",
        authorTitle: "",
        authorAvatar: "",
        quote: "",
        ctaText: "Daha Fazla",
        ctaHref: "#",
        image1: "",
        image2: "",
        image3: "",
        image4: "",
      },
    },
    {
      type: "feature-section-1",
      label: "Özellikler",
      description: "Ana ikon + başlık + 2 kolonlu özellik listesi + alt CTA kutusu",
      defaultConfig: {
        mainIcon: "heart",
        title: "Öne Çıkan Özellikler",
        subtitle: "Ürünümüzün size sunduğu temel avantajlar.",
        features: [
          { icon: "wifi-off", title: "Çevrimdışı Çalışır", description: "İnternet bağlantısı olmadan da kullanılabilir." },
          { icon: "shield-check", title: "Güvenli", description: "Uçtan uca şifreleme ile verileriniz güvende." },
          { icon: "battery-charging", title: "Enerji Dostu", description: "Pil ömrünü koruyarak çalışır." },
          { icon: "network", title: "Bağlı Kal", description: "Ağ kesilse bile cihazlar arası mesajlaşma." },
        ],
        ctaTitle: "Hazır mısınız?",
        ctaDescription: "Hemen başlayın, ihtiyacınız olan çözümü keşfedin.",
        primaryButtonText: "İndir",
        primaryButtonIcon: "download",
        primaryButtonHref: "#",
        secondaryButtonText: "Daha Fazla",
        secondaryButtonIcon: "external-link",
        secondaryButtonHref: "#",
      },
    },
    {
      type: "benchmark-charts",
      label: "Benchmark Kartları",
      description: "Çözümlerdeki performans grafiklerinin kart formatında gösterimi (bar/line/radar/area)",
      defaultConfig: {
        headline: "Performans Karşılaştırması",
        description: "",
        columns: 2,
        charts: [
          {
            title: "Render Süresi",
            chartType: "bar",
            unit: "sn",
            labels: ["STUUX Pro", "Rakip A", "Rakip B"],
            datasets: [
              { name: "Blender", color: "#10b981", values: [42, 68, 75] },
            ],
          },
        ],
      },
    },
    {
      type: "immersive-gallery",
      label: "Galeri",
      description: "Scroll ile zoom efektli immersive görsel galeri (7 slot)",
      defaultConfig: {
        headline: "",
        images: [{ src: "" }, { src: "" }, { src: "" }, { src: "" }, { src: "" }, { src: "" }, { src: "" }],
      },
    },
    {
      type: "clip-hover-grid",
      label: "Clip Hover Grid",
      description: "Hover'da dilimli görsel açığa çıkma efekti (Codrops ClipHoverEffect port)",
      defaultConfig: {
        headline: "Öne Çıkan Projeler",
        description: "",
        orientation: "vertical",
        slicesTotal: 5,
        columns: 3,
        items: [
          {
            image: "",
            date: "2026",
            title: "Proje Adı",
            linkText: "İncele",
            linkHref: "#",
          },
        ],
      },
    },
    {
      type: "conversion-integrations-section",
      label: "Entegrasyonlar Diyagramı",
      description: "Merkezi logo + bağlantı çizgileri ile entegrasyon ağı görseli",
      defaultConfig: {
        label: "ENTEGRASYONLAR",
        title: "Tek Tıkla Entegrasyon.\nSınırsız Potansiyel.",
        description:
          "STUUX; CRM, veri ambarı, analitik ve reklam araçlarınızla sorunsuz çalışır. Silolanmış verinizi AI destekli koordineli kampanyalara dönüştürür.",
        ctaText: "Demo İste",
        ctaHref: "/iletisim",
        logos: ["google", "salesforce", "snowflake", "slack", "hubspot", "zapier"],
      },
    },
    {
      type: "cta-illustration",
      label: "CTA Illustration",
      description: "Görsel + başlık + açıklama + CTA buton, ortalanmış",
      defaultConfig: {
        headline: "Hemen Başlayın",
        description: "",
        ctaText: "Teklif İste",
        ctaHref: "/iletisim",
        image: "",
        imageAlt: "",
        dark: true,
      },
    },
    // ── ST Aero Hero ──────────────────────────────────────────────────
    {
      type: "st-aero-hero-1",
      label: "ST Aero Hero",
      description: "Split layout hero: sol resim + sağ metin, avatar grubu, CTA butonu, logo marquee",
      defaultConfig: {
        headline: "Sustainable Solutions for a Better Future",
        description: "Empowering businesses and communities to thrive in a low-carbon world through tailored clean energy solutions.",
        ctaText: "Start a Project",
        ctaHref: "#",
        image: "",
        imageAlt: "",
        avatarCount: "15,000+",
        avatarLabel: "Teams Connected",
        avatarImages: [],
        logos: [],
      },
    },
    {
      type: "st-tabs",
      label: "ST Vertical Tabs",
      description: "Dikey tab'lı resim galerisi: sol tab listesi + sağ animasyonlu görsel slider",
      defaultConfig: {
        headline: "Neler Yapıyoruz",
        subtitle: "(HİZMETLER)",
        autoPlayDuration: 5000,
        items: [
          {
            id: "01",
            title: "Web Tasarım",
            description: "Güzel, işlevsel ve kullanıcı odaklı dijital deneyimler yaratıyoruz.",
            image: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200",
          },
          {
            id: "02",
            title: "Geliştirme",
            description: "Yüksek performanslı, animasyonlu web siteleri geliştiriyoruz.",
            image: "https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?q=80&w=1200",
          },
          {
            id: "03",
            title: "Marka Kimliği",
            description: "Markanızın görsel kimliğini ve sesini kalıcı bir izlenim için tanımlıyoruz.",
            image: "https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=1200",
          },
        ],
      },
    },
    {
      type: "st-lets-work",
      label: "ST Let's Work Together",
      description: "Animasyonlu CTA: tıklayınca 'Book a call' geçişi, hover efektleri",
      defaultConfig: {
        statusText: "Projeler için müsait",
        headlineLine1: "Birlikte",
        headlineLine2: "çalışalım",
        description: "Aklınızda bir proje mi var? Duymak isteriz. Birlikte olağanüstü bir şey yaratalım.",
        email: "info@stuux.com",
        successTitle: "Konuşalım",
        successSubtitle: "Harika",
        bookCallText: "Görüşme Planla",
        bookCallUrl: "",
        bookCallNote: "15 dk tanışma görüşmesi",
      },
    },
    {
      type: "st-marquee",
      label: "ST Perspective Marquee",
      description: "3D perspektif efektli kayan metin animasyonu (Remotion)",
      defaultConfig: {
        items: ["STUUX", "Workstation", "GPU Server", "Storage", "Networking", "Performance", "Reliability", "Innovation"],
        fontSize: 84,
        fontWeight: 700,
        pixelsPerFrame: 2,
        rotateY: -28,
        rotateX: 8,
        perspective: 1200,
        speed: 1,
        dark: true,
        height: "60vh",
        durationInFrames: 240,
        fps: 30,
      },
    },
    // ── Azurio Branding Studio sections ──────────────────────────────
    {
      type: "az-hero",
      label: "AZ Hero",
      description: "Full-screen hero: tag'ler, video, büyük brand yazısı (Azurio tarzı)",
      defaultConfig: {
        headline: "",
        subtext: "Ready for the game changing project?",
        brandText: "STUUX",
        tags: ["Innovations", "Excellence", "Experience", "Competence", "Passion"],
        tags2: ["UI/UX", "Hardware", "Development", "Branding", "Support"],
        contactItems: [],
        videoSrc: "",
        videoPoster: "",
        ctaText: "New Case",
        ctaHref: "#",
      },
    },
    {
      type: "az-projects-stack",
      label: "AZ Projects Stack",
      description: "Üst üste yığılan proje kartları, marquee bant + resim + tag'ler",
      defaultConfig: {
        cards: [
          { title: "Project 1", tags: ["Design", "Development"], image: "", ctaText: "Detay", ctaHref: "#" },
          { title: "Project 2", tags: ["Branding", "Marketing"], image: "", ctaText: "Detay", ctaHref: "#" },
          { title: "Project 3", tags: ["UI/UX", "Strategy"], image: "", ctaText: "Detay", ctaHref: "#" },
        ],
        marqueeItems: ["Design", "Development", "Branding", "eCommerce", "Marketing"],
      },
    },
    {
      type: "az-sticky-caption",
      label: "AZ Sticky Caption",
      description: "Büyük manifesto metni + scroll'da kayan resim galerisi",
      defaultConfig: {
        headline: "Digital agency specializing in innovative design & cutting-edge development",
        highlightedWords: ["innovative design", "development"],
        ctaText: "Services",
        ctaHref: "#",
        images: [
          { src: "", tag: "Branding" },
          { src: "", tag: "Illustrations" },
          { src: "", tag: "Photography" },
        ],
      },
    },
    {
      type: "az-sticky-images",
      label: "AZ Sticky Images",
      description: "Full-screen sticky slider: progress bar + resim + başlık geçişi",
      defaultConfig: {
        slides: [
          { title: "Strategy", image: "" },
          { title: "Design", image: "" },
          { title: "Development", image: "" },
        ],
        ctaText: "Process",
        ctaHref: "#",
      },
    },
    {
      type: "az-manifest-split",
      label: "AZ Manifest Split",
      description: "Büyük manifesto yazısı + sol resim / sağ açıklama + tag'ler",
      defaultConfig: {
        manifestText: "We are a creative web agency specializing in innovative design and cutting-edge development.",
        manifestHighlight: "We help businesses stand out and thrive in the modern landscape.",
        ctaText: "Hakkımızda",
        ctaHref: "#",
        image: "",
        imageAlt: "",
        description: "From pixel-perfect designs to flawless code, every aspect of our projects is crafted with care.",
        tags: ["Innovations", "Excellence", "Creativity", "Experience", "Competence", "Passion"],
      },
    },
    {
      type: "az-parallax-divider",
      label: "AZ Parallax Divider",
      description: "Full-width parallax görsel + overlay başlık + CTA butonu",
      defaultConfig: {
        image: "",
        imageAlt: "",
        headline: "Small but powerful team",
        ctaText: "Let's meet",
        ctaHref: "#",
        overlayOpacity: 40,
      },
    },
    {
      type: "az-blog-grid",
      label: "AZ Blog Grid",
      description: "4 sütunlu blog/haber kartları: tarih + resim + başlık",
      defaultConfig: {
        headline: "Featured news",
        description: "Inspiring ideas, creative insights, and the latest in design and tech.",
        ctaText: "News Overview",
        ctaHref: "#",
        items: [
          { title: "Frontend innovations", date: "02 February, 2026", image: "", href: "#" },
          { title: "Branding in digital experiences", date: "28 January, 2026", image: "", href: "#" },
          { title: "Elevating digital workshops", date: "15 January, 2026", image: "", href: "#" },
          { title: "Designing for the future", date: "03 January, 2026", image: "", href: "#" },
        ],
      },
    },
    {
      type: "crowd-canvas",
      label: "Crowd Canvas",
      description: "Animasyonlu yürüyen figürler canvas'i (Skiper39) — başlık + spritesheet görseli",
      defaultConfig: {
        label: "",
        headline: "KALABALIĞIN İÇİNDE KAYBOLMA",
        description: "",
        primaryCtaText: "Detaylar",
        primaryCtaHref: "#",
        secondaryCtaText: "İletişim",
        secondaryCtaHref: "/iletisim",
        imageSrc: "/images/peeps/all-peeps.png",
        rows: 15,
        cols: 7,
        height: "100vh",
        dark: false,
      },
    },
    {
      type: "masonry-gallery",
      label: "Masonry Galeri",
      description:
        "GSAP animasyonlu masonry görsel galerisi (responsive 1-5 sütun, blur-to-focus, hover scale, isteğe bağlı color shift)",
      defaultConfig: {
        label: "",
        headline: "Galeri",
        description: "",
        items: [
          { id: "1", img: "https://picsum.photos/id/1015/600/900?grayscale", url: "", height: 400 },
          { id: "2", img: "https://picsum.photos/id/1011/600/750?grayscale", url: "", height: 250 },
          { id: "3", img: "https://picsum.photos/id/1020/600/800?grayscale", url: "", height: 600 },
          { id: "4", img: "https://picsum.photos/id/1025/600/700?grayscale", url: "", height: 300 },
          { id: "5", img: "https://picsum.photos/id/1043/600/900?grayscale", url: "", height: 500 },
          { id: "6", img: "https://picsum.photos/id/1050/600/750?grayscale", url: "", height: 350 },
          { id: "7", img: "https://picsum.photos/id/1060/600/900?grayscale", url: "", height: 450 },
          { id: "8", img: "https://picsum.photos/id/1074/600/700?grayscale", url: "", height: 280 },
        ],
        ease: "power3.out",
        duration: 0.6,
        stagger: 0.05,
        animateFrom: "bottom",
        scaleOnHover: true,
        hoverScale: 0.95,
        blurToFocus: true,
        colorShiftOnHover: false,
        dark: false,
      },
    },
    {
      type: "pixel-blast-hero",
      label: "Pixel Blast Hero",
      description:
        "WebGL interaktif piksel blast arka plan (Bayer dithering + ripple + liquid distortion) — three + postprocessing",
      defaultConfig: {
        eyebrow: "INTERACTIVE BACKGROUND",
        headline: "Pixel Blast",
        description:
          "WebGL ile sürüklenen, tıklanan, dalgalanan piksel desenli interaktif arka plan. Hover ve tıkla — yüzey tepki versin.",
        primaryCtaText: "Keşfet",
        primaryCtaHref: "#",
        secondaryCtaText: "",
        secondaryCtaHref: "",
        variant: "circle",
        pixelSize: 6,
        color: "#B497CF",
        patternScale: 3,
        patternDensity: 1.2,
        pixelSizeJitter: 0.5,
        enableRipples: true,
        rippleSpeed: 0.4,
        rippleThickness: 0.12,
        rippleIntensityScale: 1.5,
        liquid: true,
        liquidStrength: 0.12,
        liquidRadius: 1.2,
        liquidWobbleSpeed: 5,
        speed: 0.6,
        edgeFade: 0.25,
        transparent: true,
        bgColor: "#070b0a",
        textColor: "#FFFFFF",
        height: "100vh",
      },
    },
    {
      type: "code-nest-hero",
      label: "CodeNest Hero (HLS Video)",
      description:
        "Koyu temalı premium hero: HLS video arka plan, liquid-glass card, grid lines, santral glow — eğitim/SaaS odaklı",
      defaultConfig: {
        videoSrc:
          "https://stream.mux.com/tLkHO1qZoaaQOUeVWo8hEBeGQfySP02EPS02BmnNFyXys.m3u8",
        eyebrow: "Career-Ready Curriculum",
        headline: "LAUNCH YOUR CODING CAREER.",
        description:
          "Master in-demand coding skills with our comprehensive curriculum. From fundamentals to advanced projects, we prepare you for the tech industry.",
        ctaLabel: "Get Started",
        ctaHref: "#",
        cardTag: "[ 2025 ]",
        cardHeadline: "Taught by Industry Professionals",
        cardItalicWord: "Industry",
        cardDescription: "Learn from engineers shipping code at scale today.",
        brandName: "CodeNest",
        showInternalNav: false,
        accent: "#5ed29c",
        bgColor: "#070b0a",
      },
    },
    {
      type: "hover-brand-logo",
      label: "Hover Brand Logo",
      description: "Hover'da marka adının animasyonlu değiştiği logo şeridi (kendi logolarını yükle)",
      defaultConfig: {
        label: "Kullananlar",
        defaultText: "öncü şirketler",
        brands: [
          { id: "brand-1", name: "Marka 1", image: "" },
          { id: "brand-2", name: "Marka 2", image: "" },
          { id: "brand-3", name: "Marka 3", image: "" },
          { id: "brand-4", name: "Marka 4", image: "" },
        ],
        dark: false,
      },
    },
    {
      type: "az-cta-marquee",
      label: "AZ CTA Marquee",
      description: "Ters renkli CTA bölümü + yatay kayan resim galerisi",
      defaultConfig: {
        headline: "Let's talk about your project",
        ctaText: "İletişim",
        ctaHref: "/iletisim",
        images: [
          { src: "", tag: "Photography" },
          { src: "", tag: "3D Models" },
          { src: "", tag: "Development" },
          { src: "", tag: "Illustrations" },
          { src: "", tag: "Fashion" },
          { src: "", tag: "Digital Art" },
        ],
        dark: true,
      },
    },
    {
      type: "liveblocks-home-hero",
      label: "Liveblocks Hero",
      description: "Siyah zemin, badge, büyük başlık, renkli özellik chip'leri, iki CTA butonu, spotlight efekti",
      defaultConfig: {
        badgeText: "Yeni",
        badgeLinkText: "v2.0",
        headline: "Ürününüzde\niş birliğini keşfedin",
        descriptionPrefix: "Ship features like",
        descriptionSuffix: "in days, not months. Engage users, fuel creativity, and drive growth.",
        features: [
          { label: "GPU Server", icon: "server", color: "#F5A623" },
          { label: "Workstation", icon: "monitor", color: "#7ED321" },
          { label: "Storage", icon: "database", color: "#BD10E0" },
          { label: "Networking", icon: "network", color: "#E74C3C" },
        ],
        primaryCtaText: "Ücretsiz Başla",
        primaryCtaHref: "/iletisim",
        secondaryCtaText: "Belgeleri Oku",
        secondaryCtaHref: "#",
        bottomImage: "",
      },
    },
    {
      type: "scroll-blur-typography",
      label: "Scroll Blur Typography",
      description: "Scroll'da kelime kelime blur'dan netliğe geçiş efekti — Codrops ScrollBlurTypography port",
      defaultConfig: {
        fontSize: "lg",
        align: "left",
        items: [
          { label: "01", text: "Birinci metin bloğu buraya gelecek. Scroll ile kelimeler tek tek belirir." },
          { label: "02", text: "İkinci metin bloğu. Her kelime bulanıktan nete doğru geçiş yapar." },
          { label: "03", text: "Üçüncü metin bloğu. Etkileyici tipografi animasyonu." },
        ],
      },
    },
    {
      type: "perspective-hero",
      label: "Perspektif Hero (3D)",
      description: "HTML içeriği Three.js sahnesine projeksiyon — scroll ile kamera döner",
      defaultConfig: {
        line1: "Designing",
        line2: "Motion",
        line3: "Crafting",
        line4: "Depth",
        line5: "Into Living",
        line6: "Worlds",
        cardTitle: "Kurumsal Donanım\nÇözümleri",
        cardDescription: "Yüksek performans iş yükleri için mühendislik odaklı yaklaşım.",
        cardFooter: "stuux.com",
        scrollLabel: "SCROLL DOWN",
        sceneBackground: "#ffffff",
        dark: false,
      },
    },
    {
      type: "customers-showcase",
      label: "Müşteriler",
      description: "Müşteri/ortak logoları — başlık, açıklama, CTA, dark/light mod",
      defaultConfig: {
        headlinePart1: "Tercih edilen",
        inlineImage1: "",
        headlinePart2: "ve güvenilen",
        inlineImage2: "",
        headlinePart3: "donanım çözümleri.",
        logoBarLabel: "Referanslarımızdan bazıları:",
        logos: [],
        description: "Kurumsal altyapı için mühendislik odaklı yaklaşım.",
        descriptionMuted: "Türkiye'nin önde gelen işletmeleri yüksek performans iş yükleri için STUUX'u tercih ediyor.",
        ctaText: "Referansları gör →",
        ctaHref: "/referanslar",
        finePrint: "Hemen başlamak için iletişime geçin.",
        finePrintHighlight: "Ücretsiz keşif görüşmesi.",
        dark: false,
      },
    },
    {
      type: "feature-carousel",
      label: "Features Carousel",
      description: "Animasyonlu özellik carousel'i — sol navigasyon + sağ görsel kart",
      defaultConfig: {
        accentColor: "#62B2FE",
        autoPlayInterval: 3000,
        features: [
          { id: "f1", label: "Yüksek Performans", image: "https://images.unsplash.com/photo-1591488320449-011701bb6704?q=80&w=1200", description: "Kurumsal iş yükleri için mühendislik odaklı donanım çözümleri." },
          { id: "f2", label: "GPU Sunucuları", image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200", description: "Yapay zeka ve derin öğrenme için optimize edilmiş GPU sistemleri." },
          { id: "f3", label: "Depolama Çözümleri", image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?q=80&w=1200", description: "Hızlı ve güvenilir NVMe tabanlı depolama altyapısı." },
          { id: "f4", label: "7/24 Destek", image: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?q=80&w=1200", description: "Uzman teknik ekibimizle kesintisiz destek hizmeti." },
          { id: "f5", label: "Özel Konfigürasyon", image: "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?q=80&w=1200", description: "İhtiyacınıza özel donanım yapılandırması ve kurulum." },
        ],
      },
    },
  ]
}
