import "dotenv/config"
import { PrismaClient } from "../src/generated/prisma"
import { PrismaPg } from "@prisma/adapter-pg"

const adapter = new PrismaPg(process.env.DATABASE_URL!)
const prisma = new PrismaClient({ adapter })

// Full specs from Airtable for each product (extracted from MCP response)
const allSpecs: Record<string, Record<string, string>> = {
  "STX-OF-XTIA-INT": {
    cpu: "Intel® Core™ Ultra Serisi", motherboard: "ROG STRIX Z890-I GAMING WIFI", chipset: "Intel Z890-I",
    formFactor: "Mini ITX", maxRam: "128", dimmSlots: "2", maxGpu: "1", m2Slots: "2", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "1100 Watt", cooling: "Hava Soğutma", coolingCapacity: "Open Frame Hava Soğutma",
    caseType: "Open Frame", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "F Serisi",
    ioPanel: "2 x Thunderbolt™ 4 (2 x USB Type-C®)\n1 x USB 20 Gbps (USB Type-C®)\n3 x USB 10 Gbps (Type A)\n1 x USB 5 Gbps (Type A)\n2 x USB 2.0 (Type A)\n1 x HDMI™\n1 x Intel® 2.5Gb Ethernet\n1 x BIOS FlashBack™",
    ethernet: "1 x Intel® 2.5Gb Ethernet",
    wireless: "Wi-Fi 7 (802.11be) 2x2\n2,4/5/6 GHz\n5,8Gbps\nBluetooth® v5.4",
    remoteManagement: "Yok",
    audio: "ROG Strix Hive II\nESS® SABRE9260Q DAC\nGümüş kaplama ses jakları",
    dimensions: "504 x 226 x 436 mm",
  },
  "STX-OF-XTIA-AMD": {
    cpu: "AMD Ryzen™ 9", motherboard: "ROG STRIX X870-I GAMING WIFI", chipset: "AMD X870",
    formFactor: "Mini ITX", maxRam: "128", dimmSlots: "2", maxGpu: "1", m2Slots: "2", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "1100 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "Open Frame", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "F Serisi",
    ethernet: "1 x Intel® 2.5Gb Ethernet",
    wireless: "Wi-Fi 7 (802.11be) 2x2\n6,5Gbps\nBluetooth® v5.4",
    remoteManagement: "Yok",
    audio: "ROG Strix Hive II\nESS® SABRE9260Q DAC",
    dimensions: "503 x 226 x 436 mm",
  },
  "STX-PT-Z890": {
    cpu: "Intel® Core™ Ultra 9", motherboard: "ProArt Z890-CREATOR WIFI", chipset: "Intel® Z890 Yonga Seti",
    formFactor: "ATX", maxRam: "256", dimmSlots: "4", maxGpu: "1", m2Slots: "5", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "1200 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "L Serisi",
    ioPanel: "2 x Thunderbolt™ 5 USB Type-C®\n1 x Thunderbolt™ 4 USB Type-C®\n6 x USB 10 Gbps (Type-A)\n1 x USB 2.0 (Type-A)\n1 x DisplayPort (Giriş)\n1 x HDMI™\n1 x Wi-Fi modülü\n1 x Marvell® 10Gb Ethernet\n1 x Intel® 2,5Gb Ethernet\n2 x Altın kaplama ses jakı",
    ethernet: "2 x Marvell® AQtion 10Gb Ethernet\n1 x Intel® 2.5Gb Ethernet",
    wireless: "Wi-Fi 7 (802.11be) 2x2\n6,5Gbps\nBluetooth® v5.5",
    remoteManagement: "Yok",
    audio: "Realtek ALC1220P 7.1 Çevresel Ses",
    dimensions: "503 x 226 x 436 mm",
  },
  "STX-PT-X870": {
    cpu: "AMD Ryzen™ 9", motherboard: "ProArt X870E-CREATOR WIFI", chipset: "AMD X870E",
    formFactor: "ATX", maxRam: "256", dimmSlots: "4", maxGpu: "1", m2Slots: "5", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "1200 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "L Serisi",
    ethernet: "5 x Marvell® AQtion 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7 (802.11be) 2x2\n6,5Gbps\nBluetooth® v5.8",
    remoteManagement: "Yok",
    audio: "Realtek ALC1220P 7.1",
    dimensions: "507 x 226 x 436 mm",
  },
  "STX-C5-INT": {
    cpu: "Intel® Core™ Ultra 9", motherboard: "ROG STRIX B860-G GAMING WIFI", chipset: "AMD B850 Yonga Seti",
    formFactor: "Mikro ATX", maxRam: "256", dimmSlots: "4", maxGpu: "1", m2Slots: "1", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "850 Watt", cooling: "240mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "M Serisi",
    ethernet: "2 x Realtek 2.5Gb Ethernet",
    wireless: "Wi-Fi 6E (802.11ax)\nBluetooth® v5.4",
    remoteManagement: "Yok",
    audio: "Realtek ALC1220P 7.1",
    dimensions: "442 x 250 x 518 mm",
  },
  "STX-C5-AMD": {
    cpu: "AMD Ryzen™ 9", motherboard: "ROG STRIX B850-F GAMING WIFI7 NEO", chipset: "AMD B850 Yonga Seti",
    formFactor: "Mikro ATX", maxRam: "256", dimmSlots: "4", maxGpu: "1", m2Slots: "1", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "850 Watt", cooling: "240mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "M Serisi",
    ethernet: "1 x Realtek 2.5Gb Ethernet",
    wireless: "Wi-Fi 6E (802.11ax)\nBluetooth® v5.3",
    remoteManagement: "Yok",
    audio: "Realtek ALC1220P 7.1",
    dimensions: "442 x 250 x 518 mm",
  },
  "STX-C7-TR": {
    cpu: "AMD Ryzen™ Threadripper™", motherboard: "Pro WS TRX50-SAGE WIFI A", chipset: "AMD TRX50",
    formFactor: "CEB", maxRam: "512", dimmSlots: "4", maxGpu: "2", m2Slots: "4", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "2000 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "X Serisi",
    ethernet: "1 x Marvell® 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7 (802.11be)\nBluetooth® v5.4",
    remoteManagement: "Yok",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "505 x 266 x 511 mm",
  },
  "STX-C7-TRP": {
    cpu: "AMD Ryzen™ Threadripper™ PRO", motherboard: "Pro WS WRX90E-SAGE SE", chipset: "AMD WRX90",
    formFactor: "EEB", maxRam: "1024", dimmSlots: "8", maxGpu: "4", m2Slots: "4", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "2X 2500 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "X Serisi",
    ethernet: "2 x Marvell® 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7\nBluetooth® v5.5",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "505 x 266 x 511 mm",
  },
  "STX-C7-EPYC": {
    cpu: "AMD EPYC™ 9005/9004", motherboard: "TURIND8X-2T/500W", chipset: "AMD SP5",
    formFactor: "EEB", maxRam: "2048", dimmSlots: "8", maxGpu: "5", m2Slots: "2", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "1X 2500W veya 2X 2500W", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "X Serisi",
    ethernet: "Broadcom BCM57416: 2X RJ45 (10GbE)",
    wireless: "Yok",
    remoteManagement: "BMC: ASPEED AST2600\nDedicated IPMI LAN",
    audio: "Yok",
    dimensions: "505 x 266 x 511 mm",
  },
  "STX-C7-XEON": {
    cpu: "Intel® Xeon® 600", motherboard: "W890D8-2L2T", chipset: "AMD W790",
    formFactor: "EEB", maxRam: "1024", dimmSlots: "8", maxGpu: "4", m2Slots: "4", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "2500 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "X Serisi",
    ethernet: "3 x Marvell® 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7\nBluetooth® v5.6",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "505 x 266 x 511 mm",
  },
  "STX-C10-EPYC": {
    cpu: "AMD EPYC™ 9005/9004", motherboard: "TURIN2D16-2T", chipset: "AMD SP6",
    formFactor: "EEB", maxRam: "2048", dimmSlots: "8", maxGpu: "5", m2Slots: "2", ssdBays: "12", hddBays: "3",
    material: "Alüminyum", psu: "2X 2500 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "E Serisi",
    ethernet: "5 x Marvell® 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7\nBluetooth® v5.8",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "581 x 262 x 658 mm",
  },
  "STX-C10-XEON": {
    cpu: "Intel® Xeon® 6700P-series", motherboard: "GNR2D16-2T", chipset: "AMD SP7",
    formFactor: "EEB", maxRam: "2048", dimmSlots: "8", maxGpu: "5", m2Slots: "2", ssdBays: "12", hddBays: "3",
    material: "Alüminyum", psu: "2X 2500 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "İş İstasyonu", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "E Serisi",
    ethernet: "6 x Marvell® 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7\nBluetooth® v5.9",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "581 x 262 x 658 mm",
  },
  "STX-GW-TRP": {
    cpu: "AMD Ryzen™ Threadripper™ PRO", motherboard: "Pro WS WRX90E-SAGE SE", chipset: "AMD SP5",
    formFactor: "EEB", maxRam: "2048", dimmSlots: "8", maxGpu: "6", m2Slots: "4", ssdBays: "4", hddBays: "4",
    material: "Alüminyum", psu: "4x 2000W Hot Swap CRPS", cooling: "360mm",
    coolingCapacity: "VRM'li CPU ve GDDR ile VRM'li GPU 6.5 kW",
    caseType: "4U Rack / Bağımsız", rackMount: "Evet", noiseLevel: "39dB - 70dB", series: "X Serisi",
    ethernet: "2x 10Gb + PCIe'de 400Gb/s'ye kadar",
    wireless: "Wi-Fi 7\nBluetooth® v5.10",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "439 x 681 x 177 mm",
    weight: "4 GPU — 49kg / 6 GPU — 52kg / 8 GPU — 55kg",
  },
  "STX-GW-XEON": {
    cpu: "Intel® Xeon® 600", motherboard: "W890D8-2L2T", chipset: "AMD SP6",
    formFactor: "EEB", maxRam: "2048", dimmSlots: "8", maxGpu: "5", m2Slots: "2", ssdBays: "4", hddBays: "4",
    material: "Alüminyum", psu: "4x 2000W Hot Swap CRPS", cooling: "360mm",
    coolingCapacity: "VRM'li CPU ve GDDR ile VRM'li GPU 6.5 kW",
    caseType: "4U Rack / Bağımsız", rackMount: "Evet", noiseLevel: "39dB - 70dB", series: "X Serisi",
    ethernet: "2x 10Gb + PCIe'de 400Gb/s",
    wireless: "Wi-Fi 7\nBluetooth® v5.11",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "439 x 681 x 177 mm",
    weight: "5 GPU — 49kg / 6 GPU — 52kg / 8 GPU — 55kg",
  },
  "STX-GG-EPYC": {
    cpu: "AMD EPYC™ 9005/9004", motherboard: "TURIN2D16-2T", chipset: "AMD SP7",
    formFactor: "EEB", maxRam: "2048", dimmSlots: "16", maxGpu: "5", m2Slots: "2", ssdBays: "4", hddBays: "4",
    material: "Alüminyum", psu: "4x 2000W Hot Swap CRPS", cooling: "360mm",
    coolingCapacity: "VRM'li CPU ve GDDR ile VRM'li GPU 6.5 kW",
    caseType: "4U Rack / Bağımsız", rackMount: "Evet", noiseLevel: "39dB - 70dB", series: "E Serisi",
    ethernet: "2x 10Gb + PCIe'de 400Gb/s",
    wireless: "Wi-Fi 7\nBluetooth® v5.12",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "439 x 681 x 177 mm",
    weight: "6 GPU — 49kg / 6 GPU — 52kg / 8 GPU — 55kg",
  },
  "STX-GG-XEON": {
    cpu: "Intel® Xeon® 6700P-series", motherboard: "GNR2D16-2T", chipset: "AMD SP8",
    formFactor: "EEB", maxRam: "2048", dimmSlots: "16", maxGpu: "5", m2Slots: "2", ssdBays: "4", hddBays: "4",
    material: "Alüminyum", psu: "4x 2000W Hot Swap CRPS", cooling: "360mm",
    coolingCapacity: "VRM'li CPU ve GDDR ile VRM'li GPU 6.5 kW",
    caseType: "4U Rack / Bağımsız", rackMount: "Evet", noiseLevel: "39dB - 70dB", series: "E Serisi",
    ethernet: "2x 10Gb + PCIe'de 400Gb/s",
    wireless: "Wi-Fi 7\nBluetooth® v5.13",
    remoteManagement: "IPMI",
    audio: "Realtek ALC1220P Surround Ses",
    dimensions: "439 x 681 x 177 mm",
    weight: "7 GPU — 49kg / 6 GPU — 52kg / 8 GPU — 55kg",
  },
  "STX-OF-XW-INT": {
    cpu: "Intel® Core™ Ultra 9", motherboard: "ROG STRIX Z890-I GAMING WIFI", chipset: "AMD X870E",
    formFactor: "Mini ITX", maxRam: "128", dimmSlots: "2", maxGpu: "1", m2Slots: "2", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "1200 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "Open Frame", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "F Serisi",
    ethernet: "4 x Marvell® 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7\nBluetooth® v5.7",
    remoteManagement: "Yok",
    audio: "Realtek ALC1220P 7.1",
    dimensions: "506 x 226 x 436 mm",
  },
  "STX-OF-XW-AMD": {
    cpu: "AMD Ryzen™ 9", motherboard: "ROG STRIX X870-I GAMING WIFI", chipset: "AMD X870E",
    formFactor: "Mini ITX", maxRam: "128", dimmSlots: "2", maxGpu: "1", m2Slots: "2", ssdBays: "2", hddBays: "2",
    material: "Alüminyum", psu: "1200 Watt", cooling: "360mm", coolingCapacity: "CPU",
    caseType: "Open Frame", rackMount: "Hayır", noiseLevel: "25dB - 35dB", series: "F Serisi",
    ethernet: "3 x Marvell® 10Gb\n1 x Intel® 2.5Gb",
    wireless: "Wi-Fi 7\nBluetooth® v5.6",
    remoteManagement: "Yok",
    audio: "Realtek ALC1220P 7.1",
    dimensions: "505 x 226 x 436 mm",
  },
}

async function main() {
  let updated = 0
  for (const [sku, specs] of Object.entries(allSpecs)) {
    const product = await prisma.product.findUnique({ where: { sku } })
    if (!product) { console.log(`  SKIP: ${sku} not found`); continue }

    await prisma.product.update({
      where: { sku },
      data: { specs: specs as never },
    })
    updated++
    console.log(`  OK: ${product.name} (${sku}) — ${Object.keys(specs).length} specs`)
  }
  console.log(`\nDone! Updated: ${updated}`)
}

main().catch(console.error).finally(() => prisma.$disconnect())
